# Generated by Django 4.2.16 on 2025-05-19 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HOME', '0003_blog_blog_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='blog_slug',
        ),
        migrations.AlterField(
            model_name='blog',
            name='photo',
            field=models.ImageField(upload_to='blog_images/'),
        ),
    ]
